<a href="https://colab.research.google.com/github/rameshawasthi/Data-Science/blob/main/Numpy__tute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction: NumPy
1.Arithmetic Operation
2.Searching,sorting,counting
3.Mathematical operation
4.Linear algebra
5.Statics operation
6.Broadcasting
7.Matrix operations
8.Sacking
9.Copy and viewing arrays
10.Bitwise Operation
11.Statistics operations

#    Python Lists                      
1. No Support for Vectorized operations.
2. No fixed type elements.                
3. For loops not efficient.               
4. Lists are built-in data structures.
5. List can hold elemetns of different types.
   **list = ["ball",1234,"cat"] -->> [str,int,str]
6. List is flexible, we add new element and expands.

                                       
# NumPy Arrays                                       
1. Supports Vectorized operations (Addition, multiplications)                                  
2. Fixed data type  
3. More efficient
4. Code is cleaner and has more advanced built-in-functions.
5. Arrays must be imported. **Import numpy as np** 
6. Arrays which can hold only data of the same data type for eg. only integers or only strings.
     
     **array = np.array([1,2,2,2,3,4]) -->> [int,int]
     

7. Numpy Array consume less memory than List. 
8. Compution is much faster than list.
9. Once we define the dimension  of an array, can not expand it anymore , limited. 
10. Same tasks with in fewer lines.
       -->Fewer loops
       -->  Advance Mathematical functions.
       
**array = np.array([1,2,3,4,5])
                                       
**Applications Of NumPy *
1.Machine Learning and computional packages
2.Essential library for scientific projects
 
**some well known library use NumPy.
    Scipy,Scikit Learn, Matplotlib, Pandas, Statsmodel
    Numpy is zero cost ; Open Source.

 **Some similar between Python list and NumPy Array.
1.Python list and  NumPy arrays have same Syntax. 
2.There elements are ordered, Mutable and are able to store duplicate items.
3.They also allow indexing, slicing and iterating.

Array Types and Conversions Between Types

In [ ]:
import numpy as np

In [ ]:
## comparision between Numpy Array and Python for loop ( Computation time)
import time
import math
import numpy as np

iter = 1000000

x = np.zeros((iter,1))
v = np.random.randn(iter,1)

before = time.time()

for i in range(iter):
    x[i] = math.exp(v[i])
after = time.time()
print(x)
print("Regular for loop= " + str((after-before)*1000) + "ms")
print('\n')
time1 = (after-before)*1000

before = time.time()
x = np.exp(v)
after = time.time()
print(x)
print("Numpy operation= " + str((after-before)*1000) + "ms")
time2 = (after-before)*1000
print('\n')
print("Numpy is "+ str(round(time1/time2,2)) + " times faster than for loop in Python.")

[[0.12141492]
 [0.67375589]
 [1.91506148]
 ...
 [2.54321501]
 [2.42290436]
 [0.39557539]]
Regular for loop= 461.8847370147705ms


[[0.12141492]
 [0.67375589]
 [1.91506148]
 ...
 [2.54321501]
 [2.42290436]
 [0.39557539]]
Numpy operation= 6.728410720825195ms


Numpy is 68.65 times faster than for loop in Python.


In [ ]:
array = np.array([2,3,4,5,10])
array

array([ 2,  3,  4,  5, 10])

In [ ]:
array[0]

2

In [ ]:
#adding new element in index one
array[1] = 100
array

array([  2, 100,   4,   5,  10])

In [ ]:
#adding nwew float point in index one.
array[1]=100.1
array

array([  2, 100,   4,   5,  10])

## 2.Numpy Array Type and Creating Numpy Array


**Array types and onversion between types
1. over come unwanted overflow, if don't define dtype.
2. memory consumption and precision which especially irrelent Machine learning algorithm.

In [ ]:
array.dtype

dtype('int32')

In [ ]:
array_dsize = np.array(array, dtype=np.int8)

In [ ]:
array_dsize

array([  2, 100,   4,   5,  10], dtype=int8)

In [ ]:
array.nbytes

20

In [ ]:
#this take 4 time less memory than array.nbytes
array_dsize.nbytes

5

In [ ]:
array_dtype = np.array([12,13,14,15,100], dtype = np.int8)
array_dtype

array([ 12,  13,  14,  15, 100], dtype=int8)

In [ ]:
array_float = np.array([1.3,4.5,8.8,10.12,90.99])
array_float


array([ 1.3 ,  4.5 ,  8.8 , 10.12, 90.99])

In [ ]:
array_float.dtype

dtype('float64')

**Multidimensional Arrays
1. The NumPy array called ndarray is the central object of the NumPy package.
2. One-dimensional array can be thought of as a vetor, Two-dimensional array as a matrix and three-dimensional arrays as a tensor, if you more than three-dimensional its simply with NumPy building functions.

In [ ]:
#two-dimensional array
twd_array=np.array([[1,2,3,4],[5,6,7,6]])
twd_array

array([[1, 2, 3, 4],
       [5, 6, 7, 6]])

In [ ]:
twd_array[0,0]

1

In [ ]:
#check dimensional of array
twd_array.ndim

2

In [ ]:
#three diminsional array
thd_array = np.array([[[1,2,3],[2,5,6],[7,8,9]]])
thd_array

array([[[1, 2, 3],
        [2, 5, 6],
        [7, 8, 9]]])

In [ ]:
thd_array.ndim

3

In [ ]:
thd_array[0,0,2]

3

**Creating arrays from lists and other Python Structure

In [ ]:
lst = [1,2,4,5,6,7,8,9]

In [ ]:
array_lst = np.array(lst)
array_lst

array([1, 2, 4, 5, 6, 7, 8, 9])

In [ ]:
nums = [1,4,5.999,-1.23,-4,99.9999]

In [ ]:
array_nums = np.array(nums)
array_nums

array([ 1.    ,  4.    ,  5.999 , -1.23  , -4.    , 99.9999])

In [ ]:
array_nums.dtype

dtype('float64')

In [ ]:
third_list = ['apple',1,2,5,'cat','dog']

In [ ]:
array_third = np.array(third_list)
array_third

array(['apple', '1', '2', '5', 'cat', 'dog'], dtype='<U11')

In [ ]:
multi_dim_list = [[[1,2,3],[3,4,5],[9,8,10]]]

In [ ]:
array_multi_dim = np.array(multi_dim_list)
array_multi_dim

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 9,  8, 10]]])

In [ ]:
tuple_nums = (1,2,4,5,6,7,100)


In [ ]:
array_tuple = np.array(tuple_nums)
array_tuple

array([  1,   2,   4,   5,   6,   7, 100])

In [ ]:
array_tuple.dtype

dtype('int32')

**Intrisic NumPy array Creation

In [ ]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
array = np.arange(10,20)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
array = np.arange(10,41,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
array = np.linspace(10,30)
array

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [ ]:
array = np.linspace(10,30,5)
array

array([10., 15., 20., 25., 30.])

In [ ]:
array_rand = np.random.rand(5,5)
array_rand

array([[0.9542999 , 0.71239093, 0.88888455, 0.90488098, 0.74325562],
       [0.33182353, 0.94763146, 0.86001134, 0.70082372, 0.30725493],
       [0.0575304 , 0.0550632 , 0.30162191, 0.6966861 , 0.28773108],
       [0.70940368, 0.86810313, 0.04617945, 0.79321346, 0.47748578],
       [0.24548673, 0.57844721, 0.32001166, 0.72051759, 0.73719348]])

In [ ]:
array_randint = np.random.randint(0,100,20)
array_randint

array([12, 16, 51, 24, 40, 36, 83,  0, 91, 60, 14, 59, 18, 85, 31, 52, 59,
       69, 16, 47])

**Creating array filled with constant values

In [ ]:
array = np.zeros(4)
array

array([0., 0., 0., 0.])

In [ ]:
array = np.zeros((4,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
array = np.ones(5)
array

array([1., 1., 1., 1., 1.])

In [ ]:
array = np.ones((5,6))
array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
array = np.ones((5,6), dtype=int)
array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
array = np.empty(10,dtype=int)
array.fill(10)
array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
array = np.full(5,10)
array

array([10, 10, 10, 10, 10])

In [ ]:
array = np.full((4,5),8)
array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

**Finding the Size and shape of an array

In [ ]:
array_first = np.arange(20)
array_first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
array_second = np.linspace((1,2),(10,20),10)
array_second

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [ ]:
array_third = np.full((2,2,2),10)
array_third

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [ ]:
array_first.shape

(20,)

In [ ]:
np.shape(array_second)

(10, 2)

In [ ]:
np.shape(array_third)

(2, 2, 2)

In [ ]:
np.size(array_first)

20

# 3.Manipulate NumPy Arrays

**Adding, Removing and Sorting elements

In [ ]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [ ]:
new_array_insert = np.insert(array,1,8) 
new_array_insert

array([1, 8, 2, 3, 4, 5, 6])

In [ ]:
new_array_append = np.append(array,10)
new_array_append

array([ 1,  2,  3,  4,  5,  6, 10])

In [ ]:
new_array_delete = np.delete(array,2)
new_array_delete 

array([1, 2, 4, 5, 6])

In [ ]:
array = np.random.randint(0,10,20)
array

array([9, 8, 0, 6, 7, 4, 7, 3, 8, 0, 2, 2, 7, 6, 5, 5, 9, 4, 6, 9])

In [ ]:
print(np.sort(array))

[0 0 2 2 3 4 4 5 5 6 6 6 7 7 7 8 8 9 9 9]


In [ ]:
#sort 2-dimensional array
array = np.array([[2,9,4,3,0],[9,4,10,11,16]])
print(np.sort(array))

[[ 0  2  3  4  9]
 [ 4  9 10 11 16]]


In [ ]:
array = np.array(['red','blues','green','orange','white','pink'])

In [ ]:
print(np.sort(array))

['blues' 'green' 'orange' 'pink' 'red' 'white']


**Copies and views of array

In [ ]:
emp_id = np.array([111,112,113,222,333])
emp_id

array([111, 112, 113, 222, 333])

In [ ]:
emp_id_reg = emp_id
print("id of employee", id(emp_id))
print("id of emp_id_reg", id(emp_id_reg))

id of employee 140299740095632
id of emp_id_reg 140299740095632


In [ ]:
emp_id_reg[1]=333
print(emp_id )
print(emp_id_reg)

[111 333 113 222 333]
[111 333 113 222 333]


In [ ]:
emp_id_cp = emp_id.copy()

In [ ]:
print(emp_id_cp)

[111 333 113 222 333]


In [ ]:
emp_id[0]=2112
print('original:', emp_id)
print('copy:', emp_id_cp)

original: [2112  333  113  222  333]
copy: [111 333 113 222 333]


**Reshaping Arrays

In [ ]:
array = np.arange(1,13)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
reshape_array = np.reshape(array,(3,4))
reshape_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
reshape_array = np.reshape(array,(6,2))
reshape_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
reshape_array = np.reshape(array,(4,5))
reshape_array   #cannot reshape array of size 12 into shape (4,5)

In [ ]:
reshape_array = np.reshape(array,(3,2,2))
print(reshape_array)
print("Dimensions of array:", reshape_array.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of array: 3


In [ ]:
reshape_array = np.array([[1,2],[2,3],[4,5],[5,6]])
reshape_array 

array([[1, 2],
       [2, 3],
       [4, 5],
       [5, 6]])

In [ ]:
reshape_array = np.reshape(array,-1)
reshape_array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Array Flat and rav fucntion.(see NumPy doc)

**Indexing and Slicing

In [ ]:
array = np.reshape(np.arange(12),(3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array[1][1]

5

In [ ]:
array[1]

array([4, 5, 6, 7])

In [ ]:
array = np.reshape(np.arange(3*4*5),(3,4,5))
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
array[0,1,2]

7

In [ ]:
array[2,-1,-1]

59

In [ ]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[3:6]

array([3, 4, 5])

In [ ]:
array[:5]

array([0, 1, 2, 3, 4])

In [ ]:
array[-3:]

array([7, 8, 9])

In [ ]:
array[::2]

array([0, 2, 4, 6, 8])

**Joining and Splitting Arrays
1.concatenate
2.stack
3.hstack
4.vstack
_____________________________
Splitting Array 
one major draw back , It will split arrays only when the number of elements is divisible by the number of splits. so the resulting arrays needs to have the same shape.
1.split
2.array_split
3.hsplit
4vsplit


In [ ]:
array = np.arange(1,10)
array1 = np.arange(11,20)
print('Array:',array)
print('Array1:',array1)

Array: [1 2 3 4 5 6 7 8 9]
Array1: [11 12 13 14 15 16 17 18 19]


In [ ]:
con_arr=np.concatenate((array,array1))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
array1 = np.array([[1,2,6,7,8],[12,13,14,15,20]])
array = np.array([[1,2,3,4,5],[16,17,18,19,20]])
print(array)
print(array1)

[[ 1  2  3  4  5]
 [16 17 18 19 20]]
[[ 1  2  6  7  8]
 [12 13 14 15 20]]


In [ ]:
con_array = np.concatenate((array1,array), axis=1)
con_array

array([[ 1,  2,  6,  7,  8,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 20, 16, 17, 18, 19, 20]])

In [ ]:
array1 = np.array([[1,2,6,7,8],[12,13,14,15,20]])
array = np.array([[1,2,3,4,5],[16,17,18,19,20]])
str_arr = np.stack((array1,array))
str_arr

array([[[ 1,  2,  6,  7,  8],
        [12, 13, 14, 15, 20]],

       [[ 1,  2,  3,  4,  5],
        [16, 17, 18, 19, 20]]])

In [ ]:
array = np.arange(1,10)
array1 = np.arange(11,20)
str_arr = np.stack((array1,array))
str_arr

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
array1 = np.array([[1,2,6,7,8],[12,13,14,15,20]])
array = np.array([[1,2,3,4,5],[16,17,18,19,20]])
str_arr = np.vstack((array1,array))
str_arr

array([[ 1,  2,  6,  7,  8],
       [12, 13, 14, 15, 20],
       [ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]])

In [ ]:
array = np.arange(1,10)
array1 = np.arange(11,20)
str_arr = np.vstack((array1,array))
str_arr

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
array = np.arange(1,13)
sp_array = np.array_split(array,4)
sp_array

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
print(sp_array[1])

[4 5 6]


In [ ]:
array = np.arange(1,13)
sp_array = np.array_split(array,8)
sp_array

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [ ]:
array = np.array([[1,2,3,4,5],[3,5,6,7,8,]])
hs_array = np.hsplit(array,5)
hs_array

[array([[1],
        [3]]),
 array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [8]])]

In [ ]:
array = np.array([[1,2,3,4,5],[3,5,6,7,8,]])
vs_array = np.vsplit(array,2)
vs_array

[array([[1, 2, 3, 4, 5]]), array([[3, 5, 6, 7, 8]])]

In [ ]:
import numpy as np

arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,3,5,7,9])

arr3 = np.concatenate((arr1, arr2), axis=0)
arr3

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

## Function and Operations

**Arthmetic Operations and Functions

*Addition       * Division
*Subtraction    * Exponentiation 
*Multiplication * Specific functions to perform them 

Vectorization -> Operation can be executed in parallel on multiple elements of the array.
               
               Benifits
*Higher performance code
*Less verbose code
*Better maintainability



In [ ]:
arr_one = np.arange(1,11)
arr_two = np.arange(41,51)
print("arr_three_add:\n", arr_one + arr_two)
print("arr_three_sub:\n", arr_one - arr_two)
print("arr_three_div:\n", arr_one / arr_two)
print("arr_three_mul:\n", arr_one *arr_two)

arr_three_add:
 [42 44 46 48 50 52 54 56 58 60]
arr_three_sub:
 [-40 -40 -40 -40 -40 -40 -40 -40 -40 -40]
arr_three_div:
 [0.02439024 0.04761905 0.06976744 0.09090909 0.11111111 0.13043478
 0.14893617 0.16666667 0.18367347 0.2       ]
arr_three_mul:
 [ 41  84 129 176 225 276 329 384 441 500]


In [ ]:
arr_three = np.arange(2,12)
print(arr_one**arr_three)

[           1            8           81         1024        15625
       279936      5764801    134217728   3486784401 100000000000]


In [ ]:
arr_one*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.add(arr_one,arr_two)

array([42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [ ]:
np.subtract(arr_three,arr_one)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.multiply(arr_one,arr_two)

array([ 41,  84, 129, 176, 225, 276, 329, 384, 441, 500])

In [ ]:
np.mod(arr_two,arr_one)

array([0, 0, 1, 0, 0, 4, 5, 0, 4, 0])

In [ ]:
np.power(arr_one,arr_three)

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [ ]:
np.sqrt(arr_one)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

**Broadcasting

*The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

*Subject to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.


   Dimesion are Compatible
__________________________________

If their axes on a one-by-one basis, they have either the same length or length of one.


In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.arange(1,4)
arr2

array([1, 2, 3])

In [ ]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
arr = np.arange(24).reshape(2,3,4)
arr1 = np.arange(4)

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr-arr1

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

**Aggregae Functions

In [ ]:
array = np.arange(10,100,10)


In [ ]:
print("sum of array:" ,array.sum())

sum of array: 450


In [ ]:
array1 = np.arange(10,110,10).reshape(2,5)

In [ ]:
print("sum of array1:",array1.sum())

sum of array1: 550


In [ ]:
array.sum(axis=0)

450

In [ ]:
array1.sum(axis=1)

array([150, 400])

In [ ]:
array.prod()

362880000000000

In [ ]:
array.prod(axis=0)

362880000000000

In [ ]:
np.average(array)

50.0

In [ ]:
np.min(array)

10

In [ ]:
np.max(array)

90

In [ ]:
np.mean(array)

50.0

In [ ]:
np.std(array)

25.81988897471611

** Unique items and Counts

In [ ]:
array = np.array([1,2,4,2,3,1,21,23,21,1,2,4,3])
np.unique(array)

array([ 1,  2,  3,  4, 21, 23])

In [ ]:
array = np.array([[1,1,2,3],[3,1,2,1],[1,1,2,3],[3,6,4,3]])
np.unique(array)

array([1, 2, 3, 4, 6])

In [ ]:
np.unique(array,axis=0)

array([[1, 1, 2, 3],
       [3, 1, 2, 1],
       [3, 6, 4, 3]])

In [ ]:
np.unique(array,axis=1) #unique column

array([[1, 1, 2, 3],
       [1, 3, 2, 1],
       [1, 1, 2, 3],
       [6, 3, 4, 3]])

In [ ]:
np.unique(array,return_index=True)

(array([1, 2, 3, 4, 6]), array([ 0,  2,  3, 14, 13]))

In [ ]:
np.unique(array,return_counts=True)

(array([1, 2, 3, 4, 6]), array([6, 3, 5, 1, 1]))

In [ ]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(array)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
array = np.arange(6).reshape(3,2)
array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.transpose(array)

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.transpose(array,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
array =  np.arange(24).reshape(2,3,4)
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.moveaxis(array,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [ ]:
np.swapaxes(array,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
array = [10,2,3,4,1,6,7,5,9]
array

[10, 2, 3, 4, 1, 6, 7, 5, 9]

In [ ]:
array[::-1]

[9, 5, 7, 6, 1, 4, 3, 2, 10]

In [ ]:
np.flip(array)

array([ 9,  5,  7,  6,  1,  4,  3,  2, 10])

In [ ]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.flip(array)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
np.flip(array,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
array = np.arange(24).reshape(2,3,4)
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.flip(array,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [ ]:
np.flip(array,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [ ]:
import numpy as np

arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,3,5,7,9])

arr1*arr2

array([ 2, 12, 30, 56, 90])

In [ ]:
import time
import math
import numpy as np

iter = 1000000

x = np.zeros((iter,1))
v = np.random.randn(iter,1)

before = time.time()

for i in range(iter):
    x[i] = math.exp(v[i])
after = time.time()
print(x)
print("Regular for loop= " + str((after-before)*1000) + "ms")
print('\n')
time1 = (after-before)*1000

before = time.time()
x = np.exp(v)
after = time.time()
print(x)
print("Numpy operation= " + str((after-before)*1000) + "ms")
time2 = (after-before)*1000
print('\n')
print("Numpy is "+ str(round(time1/time2,2)) + " times faster than for loop in Python.")

[[1.02875494]
 [1.81603255]
 [0.88391737]
 ...
 [2.23805336]
 [0.76238113]
 [0.85343682]]
Regular for loop= 739.5064830780029ms


[[1.02875494]
 [1.81603255]
 [0.88391737]
 ...
 [2.23805336]
 [0.76238113]
 [0.85343682]]
Numpy operation= 20.451068878173828ms


Numpy is 36.16 times faster than for loop in Python.


In [ ]:
arr = np.arange(10000)
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
arr.reshape(5000,2)

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       ...,
       [9994, 9995],
       [9996, 9997],
       [9998, 9999]])

In [ ]:
arr.T

array([   0,    1,    2, ..., 9997, 9998, 9999])